version: '3'
services:
  mongodb-devops:
    image: mongo
    ports:
      - "27017:27017"
    container_name: devops-db
    volumes:
      - db_data:/data/db
  nodejs-server:
    build:
      context: ./server
    ports:
      - "3003:3003"
    container_name: devops-server
    depends_on:
      - mongodb-devops
    environment:
      WAIT_HOSTS: mongodb-devops:27017
  angular-ui:
    build:
      context: ./client/angular-app
    ports:
      - "4200:4200"
    container_name: devops-ang-app
    depends_on:
      - nodejs-server
volumes:
  db_data: